name: Build

on:
  - push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 17
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          dependency-graph: generate-and-submit
        env:
          GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
      - run: ./gradlew build --scan
